### ISSUE TITLE
Many of strings tests don't pass in isolation

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#147]
```go
func main() {
	runIndexTests(strings.LastIndex, "last", IndexTest{"a☺b☻c☹d", "cx", len("a☺b☻")})
}

func runIndexTests(f func(s, sep string) int, funcName string, test IndexTest) {
	actual := f(test.s, test.sep)
	if actual != test.out {
		fmt.Printf("%s(%q,%q) = %v; want %v\n", funcName, test.s, test.sep, actual, test.out)
	}
}
```

This is code to run a single test in strings TestIndexAny, test index: 10.

On both Haxe and Golang the output is as follows:
```
last("a☺b☻c☹d","cx") = -1; want 8
```

Not sure how to approach this perhaps this is not isolated/simulated correctly. At the moment each test like this I'm skipping I've ran into. The current tests for strings where this happens are: testUnquoteInvalidUTF8, testLastIndex, testIndexAny.

**Comment by elliott5** [comment]
If a test fails in native Go, then it should also fail in go2hx ... although, of course, a test should not fail in Go.

However, as far as I can see from `strings_test.go`, the `{"a☺b☻c☹d", "cx", len("a☺b☻")}` tuple is used to test `strings.LastIndexAny` (& `strings.IndexAny`)  rather than `strings.LastIndex`.

8 is the correct output from  both of these functions for the first two fields of the tuple as input.

So has `strings.LastIndexAny` been transposed to `strings.LastIndex` somehow?

**Comment by PXshadow** [comment]
@elliott5 

It's used for both tests:

* ``TestIndexAny``: https://github.com/golang/go/blob/master/src/strings/strings_test.go#L167
* ``TestLastIndexAny``: https://github.com/golang/go/blob/master/src/strings/strings_test.go#L187

I don't see where ``strings.LastIndex`` is using this same test data however.

**Comment by elliott5** [comment]
So we agree, but then how did:
```go
	runIndexTests(strings.LastIndex, "last", IndexTest{"a☺b☻c☹d", "cx", len("a☺b☻")})
```
- a call to the wrong string function - get generated?

**Comment by PXshadow** [comment]
This is no longer an issue and probably never was, all of the tests that were being skipped for the reason of not passing in isolation are now no longer be skipping and are passing.
