### ISSUE TITLE
Github action build failing for stdgo compile

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#148]
```sh
Run npx haxe stdgo.hxml
src/StdGo.hx:20: [unicode,unicode/utf8,unicode/utf16,math,math/bits,math/rand,sort,strings,flag,io,io/fs,testing/fstest,testing/iotest,testing/internal/testdeps,os,syscall,syscall/js,log,bytes,time,path,strconv,errors,runtime,log,encoding/base64,internal/oserror,encoding,bufio,regexp,regexp/syntax,encoding/binary,reflect,math/cmplx,sync/atomic,sync,internal/bytealg,internal/cpu]
listening on local port: 6243
nodejs server started
child process exited: 2
Error: Command failed with error 2
Error: Process completed with exit code 1.
```

It's especially annoying because most of the time rerunning the action again the 2nd run this issue does not show up. I think it's linked to memory usage but I'm not sure, any idea how to fix this would be appreciated.

cc @elliott5

**Comment by elliott5** [comment]
It is difficult to see what the error actually is @PXshadow, but memory seems likely.

The simplest solution is to allocate more memory ;) ... but that is probably not possible.

If it usually works 2nd time through, what is the difference between the 1st and 2nd runs?

Are there tasks that are not done 2nd time through because files were already created 1st time through and saved in the file system for the 2nd run to use?

If this is true, how could the compilation process could be spilt to make it use less memory?

**Comment by PXshadow** [comment]
There is no difference I beleive because github action boots a fresh instance/container. Not much is happening by the time of stdgo generation and I don't know if any of the precursor steps can really be skipped when stdgo generation runs. Maybe stdgo generation itsself can be split up or I can look into optimizing it @elliott5

**Comment by elliott5** [comment]
Rethinking the mechanics of stdgo generation to use fewer memory resources would seem to be the only way forward.

**Comment by PXshadow** [comment]
This may have been fixed with macro type caching being implemented recently. I'll close for now.
