### ISSUE TITLE
Valid go code to have an ident be "true"

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#167]
```go
func (t *Tree) newBool(pos Pos, true bool) *BoolNode {
	return &BoolNode{tr: t, NodeType: NodeBool, Pos: pos, True: true}
}
```

How does Go allow this? How should go2hx handle this?

**Comment by elliott5** [comment]
Of course it looks wrong to me too, since the spec says that [`true` is a predeclared constant identifier](https://go.dev/ref/spec#Predeclared_identifiers) ... but if it is live Go it is valid.

I presume the Go compiler knows that the first use of `true` in the function signature can only be as an identifier (as constants are not permitted here), and so infers that the second use of `true` in the return statement is also as an identifier (even though `true` could also be a constant here).

The key thing for go2hx is what the Go AST says, if the Go AST says that the second (and first) use of `true` is as an identifier, then there is no problem. All we are then left with is that `true` is used as an identifier in Go but as a constant value in Haxe. You will already have code that makes sure generated go2hx identifiers do not clash with Haxe keywords, `true` needs to be added to that list.

Of course if the Go AST does not show `true` as an identifier in this context, we have bigger problems.

**Comment by PXshadow** [comment]
I believe this works now
