### ISSUE TITLE
Stdgo types need to be known by the compiler when typing.

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#39]
Go code is currently processed in a certain typing order import/types first, variables next and finally functions. This allows the compiler to know for instance``Type(10)`` being a type assertion rather then a function call. The issue comes from stdgo which is written in Haxe and passes no information to the compiler at present. 

Example : 

```go
x := time.Duration(10)
```

The compiler doesn't know that Duration is a typedef of GoInt64, and keeps in a non existent function call. So there needs to be a system that passes in this case a list of interfaces of a package. Question is how should this data be stored, and should it be generated by macros, manually or something else?

**Comment by elliott5** [comment]
I presume the issue is that the AST for the `time` (and other Haxe-implementd) Go-native package is not being generated and therefore not processed by the go2hx compiler. I am coming up against similar issues in my limited work on `reflect`.

I can see two ways forward:
1.  Generate and process the AST for the native `time` (and other Haxe-implemented) Go-native packages, then throw them away and replace the generated code with what is in the `stdgo` libraries.
2.  Write new Go `time` (and other Haxe-implemented) wrapper functions in a new Go `time` package, then call the Haxe implementation using the methods described in #24 .

Obviously I favour writing new Go wrapper packages with Haxe back-ends, because I know the approach works - TardisGo, GopherJS and TinyGo (without a back end) all use this approach.

Two other advantages of the second approach are:
- In the short term, some of the existing Go code can usually be re-used; and
- In the long term, when the project makes changes to the way the go2hx compiler generates code (e.g. changing the naming conventions), the number of changes need to be made to the Haxe `stdgo` support code will be smaller.

My experience with TardisGo was that most of the work was in writing the Haxe back end code, and then keeping it up-to-date as the Go standard library evolves.

**Comment by PXshadow** [comment]
@elliott5 you bring up very strong evidence for the second approach, and I agree, I was initally not as much in favor because I thought it could lead to more incombatibility with for instance Tardisgo bringing in go 1.4's src and modifying it (I'd be curious what was the main driver of taking that approach as well). But you're right with the second approach lots of the Go code from the standard library can be reused, such as the types, functions not using internal etc and the others can be replaced. I'll write various ideas circling in my head for calling Native Haxe from Go at #24 as now that you've set a good path to go down, I apperciate it.

**Comment by PXshadow** [comment]
This should now be able to easily be worked out with access to Go's type system now integrates into the Compiler.

**Comment by PXshadow** [comment]
This is now clearly working haha
