### ISSUE TITLE
_is_pointer_ meaning for reflect

### ISSUE THREAD

**Issue by elliott5** [go2hx/go2hx#45]
Consider this Go code:
```
	vert := Vertex{37.42202, -122.08408}
	var vertP *Vertex
	fmt.Println("---------> after init: vert=", vert, "vertP=", vertP)
	showInternals(vert, vertP)
	// output:
	// ---------> after init: vert= {37.42202 -122.08408} vertP= null
	// stdgo/reflect/Reflect.hx:1241: vert._address_=,25,vertP._address_=,null
	// stdgo/reflect/Reflect.hx:1242: vert._is_pointer_,false,vertP._is_pointer_,null

	vertP = &vert
	fmt.Println("---------> after vertp=&vert: vert=", vert, "vertP=", vertP)
	showInternals(vert, vertP)
	// output:
	// ---------> after vertp=&vert: vert= {37.42202 -122.08408} vertP= {37.42202 -122.08408}
	// stdgo/reflect/Reflect.hx:1241: vert._address_=,25,vertP._address_=,25
	// stdgo/reflect/Reflect.hx:1242: vert._is_pointer_,true,vertP._is_pointer_,true

	vertP = nil
	fmt.Println("---------> after vertP=nil: vert=", vert, "vertP=", vertP)
	showInternals(vert, vertP)
	// output:
	// ---------> after vertP=nil: vert= {37.42202 -122.08408} vertP= null
	// stdgo/reflect/Reflect.hx:1241: vert._address_=,25,vertP._address_=,null
	// stdgo/reflect/Reflect.hx:1242: vert._is_pointer_,true,vertP._is_pointer_,null
```

1) After the initialisation phase, `vert._is_pointer_==false` and `vertP==nil`. LGTM.

2) After `vertP=&vert`, both `vert` and `vertP` seem to be the same object (same `_address_`), with `_is_pointer_==true`. How can reflect know which is the pointer and which the target of that pointer?

3) After `vertP=nil`, `vert._is_pointer_==true` which suggests `vert` is still a pointer, which clearly it is not.

Am I missing something about how `_is_pointer_` works?

**Comment by PXshadow** [comment]
You're right there doesn't seem to be a distinction between the two, it seems that ``_is_pointer_`` does not produce the correct result, because classes in Haxe are pass by reference, changing ``_is_pointer_`` to true within PointerWrapper also changes it for the value type, not intended behavior.

Current idea to work around this is for PointerWrapper abstract and Pointer to have it so there is a property called _is_pointer_ as well that is always true hopefully overriding the false value of the Class version and giving a distinction from the wrapped Pointer type to the value its self.

I'll work on coding the intended behavior for this test case straight away, sorry for not having it fully fleshed out sooner, and I greatly appreciate the write up @elliott5

**Comment by elliott5** [comment]
Certainly, after the latest commits, `_is_pointer_` is never `true` when I re-ran the test ... is it still required?

I have yet to look at how the pointer functionality is now implemented, to see if `reflect` can see it at runtime.

**Comment by PXshadow** [comment]
> Is it still required?

@elliott5 I think so because PointerWrapper does not exist at runtime and therefore can't be checked at the te and PointerWrapper only wraps struct types so therefore it should be sufficent to check _is_pointer_ to see if it is wrapped or not. If you have an idea for a better way to do it, I'd be intrested.

Perhaps the cast AnyInterface macro could do the trick as well as for alias types now that I think more about it.

**Comment by elliott5** [comment]
At a philosophical level @PXshadow , I don't think any form of data can be both 'data' and 'pointer-to-data' at the same time, so I don't think `_is_pointer_` should exist.

The `cast_AnyInterface` macro proves that (most of) the required Go type information can be obtained at Haxe compile-time.  For Go named types (Haxe classes), the RunTIme Type Information system (generated by a `@:rtti` meta data tag) provides the same level of type information about its contents.  

All that is required is for go2hx to generate code which always assigns the correct Go type information to `AnyInterface`.

Go2hx already does this correctly in all of the `@:to ... AnyInterface` conversions for basic Go types, and during explicit conversions to AnyInterface using the `Go.getInterface()` macro.

However, potentially incorrect Go type information is currently generated for:
- `AnyInterface` `@:from` - "null"/"unknown" - https://github.com/go2hx/go2hx/blob/7b251156bd62b94d6737cce6e8e63770033c0d68/stdgo/StdGoTypes.hx#L1712
- `Pointer` class `@:to` -  returns `"*" + (this.get() : AnyInterface).typeName()` which may be correct for some basic Go types - https://github.com/go2hx/go2hx/blob/de135a5044891a461e18eb6df02f0d81270c9aec/stdgo/Pointer.hx#L40
- `PointerWrapper` abstract `@:to` - returns `"*" + (_value_ : AnyInterface).typeName()`  which, again, may be correct for some basic Go types - https://github.com/go2hx/go2hx/blob/de135a5044891a461e18eb6df02f0d81270c9aec/stdgo/Pointer.hx#L82

The simplest approach would be to remove the three functions above and always use the `getInterface()` macro when casting non-basic types to `AnyInterface`.  

Of course `getInterface()` will work for basic types too, so it would be cleaner, and possibly easier for go2hx code generation, if `getInterface()` was always used (and Go basic type `@:to ... AnyInterface` code made redundant).

Using the `getInterface()` for all conversions would have another important advantage: the type information in `AnyInferface` could easily be changed from being held as a `GoString` to being held as a `reflect.GT_enum` which would make Go type operations significantly faster at runtime.

**Comment by PXshadow** [comment]
I don't think any of this applies anymore with latest reflection system.
