### ISSUE TITLE
printf error on declare?

### ISSUE THREAD

**Issue by sonygod** [go2hx/go2hx#72]
```go
package main

import "fmt"

func main() {
  
   var a, b, c int

 
   a = 10
   b = 20
   c = a + b

   fmt.Printf ("result： a = %d, b = %d and c = %d\n", a, b, c) //will trace ArrayBuffer in haxe
}
```

haxe :4.2.3

go 1.16.5 windows/amd64

target: js

and target to hl also got wrong output 

```haxe
 [0,100] -> Element[%d] = %d
 [1,101] -> Element[%d] = %d
 [2,102] -> Element[%d] = %d
 [3,103] -> Element[%d] = %d
 [4,104] -> Element[%d] = %d
 [5,105] -> Element[%d] = %d
 [6,106] -> Element[%d] = %d
 [7,107] -> Element[%d] = %d
 [8,108] -> Element[%d] = %d
 [9,109] -> Element[%d] = %d
```

**Comment by PXshadow** [comment]
Latest commit correctly handles the example code you've listed, if you run into anymore fmt formatter issues feel free to post more exanples.

**Comment by sonygod** [comment]
after update ,

` characters 13-22 : Type not found : stdgo.Fmt`

I think you shoud gen s**tdgo.fmt.Fmt** instead of  **stdgo.Fm**t

**Comment by sonygod** [comment]
target  hl

wrong output . should be 20818a220 but got �����ĵ�ַ: &10



```go
package main

import "fmt"

func main() {
   var a int = 10  

   fmt.Printf("%x\n", &a  )
}
```

**Comment by elliott5** [comment]
Excellent Unicode support is one of the key advantages of `go`, which is one reason why the language is so popular in China.

As a lifelong student of 中文 myself, I would be disappointed if `go2hx` did not also provide excellent support for this and other languages.

**Comment by PXshadow** [comment]
I agree go2hx should provide excellent support for unicode across all of its targets (The underlying support will come from Haxe targets though), I'm investigating the problem at the moment, It's odd because the [try.haxe example](https://try.haxe.org/#25187a39) works however this simple program here: 
```haxe
function main() {
    trace("中文");
}
```
does not work for me on cmd or powershell on windows Haxe 4.2.3, Hashlink 1.11, and I have managed to get a few other Haxe devs to try running this program with varying results, one saying it worked on same os and same hashlink version and the other saying it did not with hashlink 1.12 on windows as well and also finding an issue in hxcpp output of the result.

So it seems pandora's box has been opened for Haxe target unicode support, I will link to the issues that come up for it.

**Comment by PXshadow** [comment]
https://github.com/HaxeFoundation/haxe/issues/9638

**Comment by PXshadow** [comment]
@sonygod try the unicode support now. Currently fmt will only support a small subset of the varbs (verbs not supported will act as if they are %v)

If anyone wants to improve support feel free to work on it and send a pull request the code is [here](https://github.com/go2hx/go2hx/blob/1c34d73e8858342f8c63b5d8861ca64253807334/stdgo/fmt/Fmt.hx#L60-L129), should be rather nice and painless to add more verbs to the formatter.

**Comment by PXshadow** [comment]
Std Fmt will be compiled by go2hx in the future, as such no more help is required for a hand written implementation.

**Comment by PXshadow** [comment]
Latest version compiles fmt, and gets the correct result, with some latest improvement to js support.

@sonygod Here is a quick command to test it assuming the test code above is called ``main.go``:
```sh
haxelib run go2hx ./main.go --js main.js
```

```sh
node main.js
result： a = 10, b = 20 and c = 30
```
