### ISSUE TITLE
Rest<T> arguments to become Slice<T> for type.

### ISSUE THREAD

**Issue by PXshadow** [go2hx/go2hx#73]
```haxe
var x:Slice<AnyInterface> -> { var n : GoInt; var err : stdgo.Error; } = stdgo.fmt.Fmt.println;
```
``
have: (haxe.Rest<...>) -> ...
want: (stdgo.Slice<...>) -> ...
``

abstract ``@:from`` for Rest -> Slice does not work, I'm not sure of a good way to represent the type.

**Comment by elliott5** [comment]
Since `haxe.Rest` requires special Haxe compiler processing, it is not too surprising that abstract `@:from` does not work.

Presumably `haxe.Rest` is required in order to easily model the variadic function "`stdgo.fmt.Fmt.println`". Because it is part of the `go2hx` runtime, the conversion could be hand-written as the first part of the function.

In the general case (assuming code must be generated using `haxe.Rest`), the conversion could be auto-generated at the start of each function with variadic arguments. 

By re-writing the parameters, extra code would be generated of course, but some of this might be removed during compiler optimisation. The important thing at this stage of the project is to get a working system, speeding it up can come later.
